### ISSUE TITLE
Another app owns sound device

### ISSUE THREAD

**Issue by bauernjunges** [flathub/app.pianocheetah.pianocheetah#3]
```
Another app owns sound device.
So no Syn till you close that app and restart PianoCheetah :(
```

Completely locked out until i delete pianocheetah/device/device.txt so i can access the MidiCfg

my sound device is Steinberg UR22mkII using pipewire

_*Edit: I'm an idiot. I can just open WineCfg from application menu. But i'm still unable to use my sound device_

**Comment by Stephen-Hazel** [comment]
Wow - i wish github would email me about stuff like this...  My apologies for takin forever.

Well, PIanoCheetah only uses ALSA.  (for syn's audio device and for midi devices).  
You need to find which app is using that sound device and clooose it.
Unfortunately, there's no GREAT way to find the app that I know of.
But it's usually chrome playing youtube or a game or something.

You can also set syn to OFF in midicfg (bottom pick in the list) if you have midi devices to do the audio with and don't need syn.

Is there aaany other sound device you can try (like an HDMI one or somethin?)  Just to try....

In pianocheetah's settings (top left green check icon), you can turn debugging on.
Then look in your home dir's
.var/app/app.pianocheetah.pianocheetah/config/dbg.txt
 
It won't tell you WHICH app to close.  But it gives more details.
(My apologies for that dumb path, but that's flatpak's fault)

Please let me know how you get on - I'd like to get ya setup :)

You can get me faster at stephen.hazel@hey.com

thanks for tryin PianoCheetah :)

**Comment by Stephen-Hazel** [comment]
well, I can't consider this a bug.  If some other app has grabbed the sound device you wanna let syn use, it does pop a dialog showing what's up...  So I think I'm a closin' it.  please email for further help if you need it - I'd be happy to give you further ideas to try.
 
OK!  your little speaker icon controlling volume - click it - there's a device tab and application tab - application tab will list all possible windows that have grabbed the sound devices.
